### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by komma-d** [FriendsOfShopware/FroshProductCompare#12]
das Plugin hat eine vergleichsweise sehr hohe Ladezeit. 
Kann man hier was verbessern?

<img width="760" alt="Bildschirmfoto 2020-11-13 um 16 56 46" src="https://user-images.githubusercontent.com/7209213/99092370-576bb080-25d1-11eb-9542-12ae56f4ab5f.png">

**Comment by vienthuong** [comment]
Hi @komma-d 
Correct me if I'm wrong, not sure if it's a problem here since the plugin's [base.html.twig](https://github.com/FriendsOfShopware/FroshProductCompare/blob/master/src/Resources/views/storefront/base.html.twig) extends the platform base.html.twig, and it basically just add an Html button and some js addition, if we removed it, the load time would not be affected much.
@shyim any idea?

**Comment by shyim** [comment]
As your graph already says. the 97% comes from core
